CREATE DATABASE GameHub;
USE GameHub;

CREATE TABLE CUSTOMER (
    CUS_ID INT(4) PRIMARY KEY,
    CUS_FNAME VARCHAR(30) NOT NULL,
    CUS_LNAME VARCHAR(30) NOT NULL,
    CUS_EMAIL VARCHAR(30) NOT NULL UNIQUE,
    CUS_ADDRESS VARCHAR(30) NOT NULL
);

CREATE TABLE VENDOR (
    VENDOR_ID INT(4) PRIMARY KEY,
    VENDOR_NAME VARCHAR(20) NOT NULL, 
    VENDOR_PHONE VARCHAR(30)
);

CREATE TABLE CATEGORY (
    CAT_ID INT(4) PRIMARY KEY,
    CAT_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE PRODUCT (
    PROD_ID INT(4) PRIMARY KEY,
    PROD_NAME VARCHAR(20) NOT NULL,
    PROD_PRICE DECIMAL(6,2) NOT NULL,
    VENDOR_ID INT(4) NOT NULL,
    CAT_ID INT(4) NOT NULL,
    FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR(VENDOR_ID),
    FOREIGN KEY (CAT_ID) REFERENCES CATEGORY(CAT_ID)
);

CREATE TABLE GAME_GENRE (
    GENRE_ID INT(4) PRIMARY KEY,
    GENRE_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE PRODUCT_GENRE (
    PROD_ID INT(4) NOT NULL,
    GENRE_ID INT(4) NOT NULL,
    PRIMARY KEY (PROD_ID, GENRE_ID),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID),
    FOREIGN KEY (GENRE_ID) REFERENCES GAME_GENRE(GENRE_ID)
);

CREATE TABLE PLATFORM (
    PLATFORM_ID INT(4) PRIMARY KEY,
    PLATFORM_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE PHYSICAL_PROD (
    PROD_ID INT(4) PRIMARY KEY,
    SHIPPING_WEIGHT DECIMAL(10,2),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID)
);

CREATE TABLE SUBSCRIPTION_PROD (
    PROD_ID INT(4) PRIMARY KEY,
    DURATION VARCHAR(15),
    SUB_TYPE VARCHAR(15),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID)
);

CREATE TABLE DIGITAL_PROD (
    PROD_ID INT(4) PRIMARY KEY,
    PLATFORM_ID INT(4) NOT NULL,
    DOWNLOAD_SIZE VARCHAR(10),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID),
    FOREIGN KEY (PLATFORM_ID) REFERENCES PLATFORM(PLATFORM_ID)
);

CREATE TABLE INVENTORY (
    PROD_ID INT(4) PRIMARY KEY,
    QTY_AVAILABLE INT(5) NOT NULL,
    LAST_UPDATED DATE,
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID)
);

CREATE TABLE INVOICE (
    INV_ID INT(4) PRIMARY KEY,
    INV_DATE DATE NOT NULL,
    INV_TOTAL DECIMAL(8,2), -- Derived
    CUS_ID INT(4) NOT NULL,
    FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID)
);

CREATE TABLE INVOICE_ITEM (
    INV_ITEM_ID INT(4) PRIMARY KEY,
    QUANTITY INT(5) NOT NULL,
    PRICE DECIMAL(8,2) NOT NULL,
    INV_ID INT(4) NOT NULL,
    PROD_ID INT(4) NOT NULL,
    FOREIGN KEY (INV_ID) REFERENCES INVOICE(INV_ID),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID)
);

CREATE TABLE PAYMENT (
    PAYMENT_ID INT(4) PRIMARY KEY,
    PAYMENT_TYPE VARCHAR(15), 
    PAYMENT_DATE DATE NOT NULL,
    PAYMENT_AMOUNT DECIMAL(8,2) NOT NULL,
    INV_ID INT(4) NOT NULL,
    FOREIGN KEY (INV_ID) REFERENCES INVOICE(INV_ID)
);

-- 500 rows
--  CUSTOMER, PRODUCT, INVOICE, INVOICE_ITEM, PAYMENT
-- Cryptocurrency,Cash,Check,Bank Transfer,Credit Card,Debit Card,Online Banking
--Insert data to tables
